### PR TITLE
Tidy up the UI code base

### PR DESCRIPTION
**Pull request by Mullefa**
Most stuff that is removed won't need to be re-added. An exception to this is the testing libraries which we will want to re-add in the future. See the diff of `package.json` for what we want to re-add.

### CODE REVIEW

**Comment by Mullefa** [comment]
@joelochlann do you know what the following do?

1. `images.d.ts`
2. `src/logo.svg`

**Review by joelochlann — APPROVED** [review]
Nice. Could probably get rid of `logo.svg` too!

**Comment by joelochlann** [comment]
logo.svg is the React logo... it can go

**Comment by joelochlann** [comment]
not exactly sure about `images.d.ts`

**Pull request merged**
